# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :shell, :path => "vagrant_bootstrap.sh"

  config.vm.hostname = "one-box-example"

  # Forward local port 8080 to guest port 80
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Virtualbox specific tweaks
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", 512]
  end
end
