# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define :web do |web_config|
    web_config.vm.box = "precise64"
    web_config.vm.host_name = "web.moz.local"
    web_config.vm.network :hostonly, "192.168.50.10"
    web_config.vm.provision :shell, :path => "web_bootstrap"
  end

  config.vm.define :db do |db_config|
    db_config.vm.box = "precise64"
    db_config.vm.host_name = "db.moz.local"
    db_config.vm.network :hostonly, "192.168.50.11"
    db_config.vm.provision :shell, :path => "db_bootstrap"
  end
end
